name: sqlite_dart_native
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  ffi: ^2.1.0
  logging: ^1.2.0
  native_assets_cli: ^0.2.0
  native_toolchain_c: ^0.2.2

dev_dependencies:
  ffigen: ^9.0.1
  http: ^1.1.0
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  output: lib/src/sqlite_bindings.dart
  preamble: |
    // ignore_for_file: unused_element
  headers:
    entry-points:
      - src/sqlite/sqlite3.h
      - src/sqlite/sqlite3ext.h
  ffi-native:
  functions:
    leaf:
      include:
        - '.*'
  compiler-opts:
    - '-DSQLITE_OMIT_DEPRECATED'
