name: sqlite_dart_native
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  ffi: ^2.1.0
  logging: ^1.2.0
  native_assets_cli: ^0.2.0
  native_toolchain_c: ^0.2.2

dev_dependencies:
  ffigen: ^9.0.1
  http: ^1.1.0
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  output: lib/src/sqlite_bindings.dart
  preamble: |
    // ignore_for_file: unused_element
  headers:
    entry-points:
      - src/sqlite/sqlite3.h
  ffi-native:
  functions:
    # TODO: Consider listing leaf functions explicitly to ensure that we don't
    #       accidentally include a function that calls a Dart callback.
    leaf:
      include:
        - '.*'
      exclude:
        # These functions might call the Dart destructor of an extension function.
        - sqlite3_create_function_v2
        - sqlite3_close
        # This functions might call the Dart callback of an extension function.
        - sqlite3_step
  compiler-opts:
    - '-DSQLITE_OMIT_DEPRECATED'
