name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DART_SDK: dev
  FLUTTER_CHANNEL: master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK }}

      - name: Check formatting
        run: dart format --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Get dependencies
        run: dart pub get

      - name: Get dependencies for flutter_example
        working-directory: example/flutter_example
        run: flutter pub get

      - name: Analyze
        run: dart analyze --fatal-infos

  # Verify that FFI bindings can be generated.
  generate_ffi_bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK }}

      - name: Get dependencies
        run: dart pub get

      - name: Generate FFI bindings
        run: dart --enable-experiment=native-assets run ffigen

  unit_tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK }}

      - name: Get dependencies
        run: dart pub get

      - name: Tests
        run: dart --enable-experiment=native-assets test

  flutter_unit_tests:
    strategy:
      matrix:
        os:
          # TODO: Enable more platforms once Flutter supports native assets on them.
          - ubuntu-latest
          - macos-latest
          # - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Enable native assets in Flutter
        run: flutter config --enable-native-assets

      - name: Get dependencies
        working-directory: example/flutter_example
        run: flutter pub get

      - name: Tests
        working-directory: example/flutter_example
        run: flutter test
