name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: dev

      - name: Get dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Generate FFI bindings
        run: dart --enable-experiment=native-assets run ffigen

      - name: Analyze
        run: dart analyze --fatal-infos

      - name: Tests
        run: dart --enable-experiment=native-assets test
